export { default as StartScreen } from '../StartScreen';
export { default as LoginScreen } from '../Login';
export { default as AmReg } from '../Registration/AmReg';
export { default as BDReg } from '../Registration/BDReg';
export { default as DocReg } from '../Registration/DocReg';
export { default as LaReg } from '../Registration/LaReg';
export { default as PaReg } from '../Registration/PaReg';
export { default as PharReg } from '../Registration/PharReg';
export { default as ResetPasswordScreen } from '../ResetPasswordScreen';
export { default as Dashboard } from '../Dashboard';
export { default as SplashScreen } from '../SplashScreen';
export { default as Doctor } from '../Doctor';
export { default as NotificationsTab } from '../NotificationsTab';
export {default as DocProfile} from '../Doctor/DocProfile';